#!/usr/bin/env node
/* OmniMark site server + admin API. Zero dependencies — Node 18+.
   - Serves the static site (clean URLs, 404 page, security headers) and
     injects admin-set <title> / description / og tags into pages on the fly.
   - /admin is the editor sign-in; /admin-advanced.html is the developer dashboard.
   - Persists to data/site.json (+ regenerates data/site.js, sitemap.xml
     and robots.txt so a plain static host still gets the saved state),
     data/admin.json (password hash + session secret) and
     data/submissions.json (contact / teardown / newsletter forms).

   Run:  node server.js            (PORT=3000 by default)
   Env:  PORT, HOST, ADMIN_PASSWORD (only read on first run, when
         data/admin.json does not exist yet). */
'use strict';
const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = __dirname;
const DATA = path.join(ROOT, 'data');
const SITE_JSON = path.join(DATA, 'site.json');
const SITE_JS = path.join(DATA, 'site.js');
const ADMIN_JSON = path.join(DATA, 'admin.json');
const SUBS_JSON = path.join(DATA, 'submissions.json');
const DRAFT_JSON = path.join(DATA, 'draft.json');
const PORT = parseInt(process.env.PORT, 10) || 3000;
/* local dev binds to loopback; a platform that injects PORT (Railway, Render,
   Fly…) needs 0.0.0.0 or its proxy can't reach the process */
const HOST = process.env.HOST || (process.env.PORT ? '0.0.0.0' : '127.0.0.1');
const TRUST_PROXY = process.env.TRUST_PROXY === '1';
const COOKIE = 'om_admin';
const SESSION_TTL = 1000 * 60 * 60 * 12; // 12h
const MAX_BODY = 2 * 1024 * 1024;        // 2 MB — site.json with full copy overrides
const PRIVATE_FILES = new Set(['admin.json', 'submissions.json', 'draft.json']);

const MIME = {
  '.html': 'text/html; charset=utf-8', '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8', '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml', '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg',
  '.gif': 'image/gif', '.webp': 'image/webp', '.ico': 'image/x-icon', '.txt': 'text/plain; charset=utf-8',
  '.xml': 'application/xml; charset=utf-8', '.woff': 'font/woff', '.woff2': 'font/woff2',
  '.mp4': 'video/mp4', '.webm': 'video/webm', '.pdf': 'application/pdf'
};

/* ---------- storage ---------- */
function readJson(file, fallback){
  try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch (e) { return fallback; }
}
function writeTextAtomic(file, text){
  const tmp = file + '.' + process.pid + '.tmp';
  fs.writeFileSync(tmp, text);
  fs.renameSync(tmp, file);
}
function writeJsonAtomic(file, obj){ writeTextAtomic(file, JSON.stringify(obj, null, 2) + '\n'); }
const DEFAULT_SITE = {
  version: 1, updatedAt: null,
  settings: {
    siteName: 'OmniMark', siteUrl: 'https://www.omnimark.com', defaultLang: 'en',
    email: 'hello@omnimark.com', phone: '+1 (800) 555-1234', phoneHref: '+18005551234',
    address: '400 Commerce St, Austin, TX 78701', addressLine1: '400 Commerce St', addressLine2: 'Austin, TX 78701',
    geoEmail: 'austin@omnimark.com', linkedin: 'https://www.linkedin.com', privacyUrl: '', termsUrl: '',
    schedulerUrl: '', ogImage: '', megaMenuLinkLimit: 4
  },
  features: { langSwitch: true, newsletter: true, cookieBanner: true, careersButton: true, showVerifiedProof: false, customCursor: true,
    magneticButtons: true, kineticHeadlines: true, marquee: true, countUp: true, reveal: true },
  design: { tokens: {}, fontDisplay: 'Bricolage Grotesque', fontBody: 'Inter', fontMono: 'JetBrains Mono',
    fontPreset: 'bricolage-inter', motion: 'on', customCss: '' },
  analytics: { gaId: '', consentScript: '' },
  structured: { orgLegalName: '', orgLogoUrl: '', articleAuthor: '', articleDatePublished: '', articleDateModified: '',
    jobTitle: '', jobDescription: '', jobDatePosted: '', jobValidThrough: '', jobEmploymentType: '', jobLocation: '', jobRemote: false, jobApplyUrl: '' },
  hiddenSections: [], sectionOrder: {}, sectionAccent: {}, itemOrder: {}, hiddenItems: [],
  pages: {}, i18n: { en: {}, az: {} },
  engines: null, enginesAz: null, industries: null, industriesAz: null
};
function loadSite(){ return Object.assign({}, DEFAULT_SITE, readJson(SITE_JSON, {})); }

/* Everything the browser will evaluate as JS — keep "</script" from
   terminating the tag. */
function siteToJs(site){
  return '/* GENERATED by server.js from data/site.json — do not edit by hand.\n' +
    '   Loaded in <head> on every page so js/site-config.js can apply the\n' +
    '   admin-saved design + content before first paint. */\n' +
    'window.OMNI_SITE = ' + JSON.stringify(site, null, 2).replace(/<\//g, '<\\/') + ';\n';
}
function listPages(){
  return fs.readdirSync(ROOT).filter(f => /\.html$/i.test(f) && !['admin.html', 'admin-advanced.html', '404.html'].includes(f)).sort();
}
function writeSeoFiles(site){
  const base = String((site.settings && site.settings.siteUrl) || '').replace(/\/+$/, '');
  const today = new Date().toISOString().slice(0, 10);
  const urls = listPages().map(f => {
    const loc = base + '/' + (f === 'index.html' ? '' : f);
    return '  <url><loc>' + escapeXml(loc) + '</loc><lastmod>' + today + '</lastmod></url>';
  });
  writeTextAtomic(path.join(ROOT, 'sitemap.xml'),
    '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + urls.join('\n') + '\n</urlset>\n');
  writeTextAtomic(path.join(ROOT, 'robots.txt'),
    /* data/site.js must stay crawlable — it carries the published copy */
    'User-agent: *\nAllow: /\nDisallow: /admin.html\nDisallow: /admin-advanced.html\nDisallow: /api/\n\nSitemap: ' + base + '/sitemap.xml\n');
}
function saveSite(site){
  site.updatedAt = new Date().toISOString();
  writeJsonAtomic(SITE_JSON, site);
  writeTextAtomic(SITE_JS, siteToJs(site));
  writeSeoFiles(site);
  return site;
}
function escapeXml(s){ return String(s).replace(/[<>&'"]/g, c => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', "'": '&apos;', '"': '&quot;' }[c])); }
function escapeHtml(s){ return String(s).replace(/[<>&"]/g, c => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;' }[c])); }

/* ---------- validation of an incoming site config ---------- */
function isPlain(o){ return o && typeof o === 'object' && !Array.isArray(o); }
function strMap(o, max){
  const out = {};
  if (!isPlain(o)) return out;
  for (const k of Object.keys(o)){
    if (typeof o[k] === 'string' && k.length <= 200 && o[k].length <= (max || 20000)) out[k] = o[k];
  }
  return out;
}
function cleanEngines(arr){
  if (!Array.isArray(arr) || !arr.length || arr.length > 8) return null;
  return arr.map((e, i) => {
    if (!isPlain(e)) e = {};
    const s = k => typeof e[k] === 'string' ? e[k].slice(0, 500) : '';
    return {
      id: (s('id') || 'engine-' + (i + 1)).replace(/[^a-z0-9-]/gi, '').slice(0, 60) || 'engine-' + (i + 1),
      num: s('num') || ('0' + (i + 1)).slice(-2),
      name: s('name'), codename: s('codename'), promise: s('promise'), headline: s('headline'),
      href: s('href') || 'services.html', detail: s('detail') || s('href') || 'services.html',
      groups: (Array.isArray(e.groups) ? e.groups : []).slice(0, 8).map(g => ({
        title: isPlain(g) && typeof g.title === 'string' ? g.title.slice(0, 200) : '',
        items: (isPlain(g) && Array.isArray(g.items) ? g.items : []).filter(x => typeof x === 'string').map(x => x.slice(0, 300)).slice(0, 40)
      }))
    };
  });
}
function cleanStrArray(arr, max){
  if (!Array.isArray(arr) || !arr.length) return null;
  return arr.filter(x => typeof x === 'string').map(x => x.slice(0, 200)).slice(0, max || 60);
}
function cleanIdArray(arr, max){
  if (!Array.isArray(arr)) return [];
  return Array.from(new Set(arr.filter(x => typeof x === 'string' && /^[a-z0-9-]{1,40}$/.test(x)))).slice(0, max || 60);
}
const FONT_PRESETS = {
  'bricolage-inter': ['Bricolage Grotesque', 'Inter', 'JetBrains Mono'],
  'sora-dmsans': ['Sora', 'DM Sans', 'Fira Code'],
  'syne-manrope': ['Syne', 'Manrope', 'IBM Plex Mono'],
  'playfair-worksans': ['Playfair Display', 'Work Sans', 'Space Mono']
};
const MOTION_FLAGS = ['customCursor', 'magneticButtons', 'kineticHeadlines', 'marquee', 'countUp', 'reveal'];
function validateSite(input){
  if (!isPlain(input)) throw new Error('config must be an object');
  const site = JSON.parse(JSON.stringify(DEFAULT_SITE));
  site.settings = Object.assign({}, site.settings, strMap(input.settings, 2000));
  const megaMenuLinkLimit = Number.parseInt(input.settings && input.settings.megaMenuLinkLimit, 10);
  site.settings.megaMenuLinkLimit = Number.isFinite(megaMenuLinkLimit) ? Math.max(1, Math.min(12, megaMenuLinkLimit)) : 4;
  if (!['en', 'az'].includes(site.settings.defaultLang)) site.settings.defaultLang = 'en';
  /* links the public pages will render as href — no javascript:/data: schemes */
  const safeLink = (v, schemes) => {
    v = String(v || '').trim();
    if (!v || v === '#' || /^(\/|\.\/|[a-z0-9-]+\.html)/i.test(v)) return v;
    const m = v.match(/^([a-z][a-z0-9+.-]*):/i);
    return m && schemes.includes(m[1].toLowerCase()) ? v : '';
  };
  for (const k of ['linkedin', 'privacyUrl', 'termsUrl']) site.settings[k] = safeLink(site.settings[k], ['http', 'https', 'mailto', 'tel']);
  for (const k of ['siteUrl', 'ogImage']) site.settings[k] = /^https?:\/\//i.test(site.settings[k] || '') ? site.settings[k].trim() : '';
  site.settings.schedulerUrl = /^https:\/\//i.test(site.settings.schedulerUrl || '') ? site.settings.schedulerUrl.trim() : '';
  if (isPlain(input.features)) for (const k of Object.keys(site.features)) if (k in input.features) site.features[k] = !!input.features[k];
  if (isPlain(input.design)){
    site.design.tokens = strMap(input.design.tokens, 200);
    for (const k of Object.keys(site.design.tokens)) if (!/^--[a-z0-9-]{1,40}$/i.test(k)) delete site.design.tokens[k];
    for (const k of ['fontDisplay', 'fontBody', 'fontMono']) if (typeof input.design[k] === 'string') site.design[k] = input.design[k].slice(0, 80);
    if (typeof input.design.fontPreset === 'string' && FONT_PRESETS[input.design.fontPreset]){
      site.design.fontPreset = input.design.fontPreset;
      const fonts = FONT_PRESETS[input.design.fontPreset];
      site.design.fontDisplay = fonts[0]; site.design.fontBody = fonts[1]; site.design.fontMono = fonts[2];
    }
    if (['on', 'calm', 'off'].includes(input.design.motion)){
      site.design.motion = input.design.motion;
      MOTION_FLAGS.forEach(k => { site.features[k] = input.design.motion === 'on'; });
      if (input.design.motion === 'calm'){
        site.features.countUp = true; site.features.reveal = true;
      }
    }
    if (typeof input.design.customCss === 'string') site.design.customCss = input.design.customCss.slice(0, 200000);
  }
  if (isPlain(input.analytics)){
    if (typeof input.analytics.gaId === 'string') site.analytics.gaId = input.analytics.gaId.trim().slice(0, 40);
    if (typeof input.analytics.consentScript === 'string') site.analytics.consentScript = input.analytics.consentScript.slice(0, 50000);
  }
  if (isPlain(input.structured)){
    site.structured = Object.assign({}, site.structured, strMap(input.structured, 10000));
    site.structured.jobRemote = !!input.structured.jobRemote;
    for (const k of ['orgLogoUrl', 'jobApplyUrl']) site.structured[k] = /^https?:\/\//i.test(site.structured[k] || '') ? site.structured[k].trim() : '';
    for (const k of ['articleDatePublished', 'articleDateModified', 'jobDatePosted', 'jobValidThrough']){
      const v = String(site.structured[k] || '').trim();
      site.structured[k] = /^\d{4}-\d{2}-\d{2}$/.test(v) && !Number.isNaN(Date.parse(v + 'T00:00:00Z')) ? v : '';
    }
    const employment = String(site.structured.jobEmploymentType || '').toUpperCase();
    site.structured.jobEmploymentType = ['FULL_TIME', 'PART_TIME', 'CONTRACTOR', 'TEMPORARY', 'INTERN', 'VOLUNTEER', 'PER_DIEM', 'OTHER'].includes(employment) ? employment : '';
  }
  site.hiddenSections = cleanStrArray(input.hiddenSections, 500) || [];
  if (isPlain(input.sectionOrder)) for (const page of Object.keys(input.sectionOrder)){
    if (!/^[a-z0-9-]{1,60}$/i.test(page) || !Array.isArray(input.sectionOrder[page])) continue;
    site.sectionOrder[page] = Array.from(new Set(input.sectionOrder[page]
      .filter(key => typeof key === 'string' && key.length <= 60))).slice(0, 60);
  }
  if (isPlain(input.sectionAccent)) for (const key of Object.keys(input.sectionAccent)){
    if (key.length <= 60 && Number.isInteger(input.sectionAccent[key]) && input.sectionAccent[key] >= 1 && input.sectionAccent[key] <= 5){
      site.sectionAccent[key] = input.sectionAccent[key];
    }
  }
  if (isPlain(input.itemOrder)) for (const key of Object.keys(input.itemOrder)){
    if (/^[a-z0-9.-]{1,60}$/.test(key)) site.itemOrder[key] = cleanIdArray(input.itemOrder[key], 60);
  }
  if (Array.isArray(input.hiddenItems)){
    site.hiddenItems = Array.from(new Set(input.hiddenItems.filter(value => typeof value === 'string' &&
      /^[a-z0-9.-]{1,60}:[a-z0-9-]{1,40}$/.test(value)))).slice(0, 500);
  }
  if (isPlain(input.pages)) for (const k of Object.keys(input.pages)){
    if (!/^[a-z0-9-]{1,60}$/i.test(k) || !isPlain(input.pages[k])) continue;
    const p = strMap(input.pages[k], 1000);
    if (Object.keys(p).length) site.pages[k] = p;
  }
  if (isPlain(input.i18n)){ site.i18n.en = strMap(input.i18n.en); site.i18n.az = strMap(input.i18n.az); }
  site.engines = cleanEngines(input.engines);
  site.enginesAz = site.engines ? cleanEngines(input.enginesAz) : null;
  site.industries = cleanStrArray(input.industries);
  site.industriesAz = site.industries ? cleanStrArray(input.industriesAz) : null;
  return site;
}

function readDraft(){
  const record = readJson(DRAFT_JSON, null);
  if (!record || !isPlain(record.draft)) return null;
  return { draft: record.draft, savedAt: record.savedAt || null };
}
function removeDraft(){
  try { fs.rmSync(DRAFT_JSON, { force: true }); } catch (e) { if (e.code !== 'ENOENT') throw e; }
}
function flatten(value, prefix, out){
  out = out || {};
  prefix = prefix || '';
  if (Array.isArray(value) || !isPlain(value)){
    out[prefix] = JSON.stringify(value);
    return out;
  }
  const keys = Object.keys(value);
  if (!keys.length) out[prefix] = '{}';
  keys.forEach(key => flatten(value[key], prefix ? prefix + '.' + key : key, out));
  return out;
}
function diffCount(before, after){
  const a = flatten(before), b = flatten(after);
  return Array.from(new Set(Object.keys(a).concat(Object.keys(b)))).filter(key => a[key] !== b[key]).length;
}
function publishSummary(before, after){
  return {
    texts: diffCount(before.i18n || {}, after.i18n || {}),
    sections: diffCount({ order: before.sectionOrder || {}, hidden: before.hiddenSections || [], accent: before.sectionAccent || {} },
      { order: after.sectionOrder || {}, hidden: after.hiddenSections || [], accent: after.sectionAccent || {} }),
    items: diffCount({ order: before.itemOrder || {}, hidden: before.hiddenItems || [] },
      { order: after.itemOrder || {}, hidden: after.hiddenItems || [] }),
    catalogue: diffCount({ engines: before.engines, enginesAz: before.enginesAz, industries: before.industries, industriesAz: before.industriesAz },
      { engines: after.engines, enginesAz: after.enginesAz, industries: after.industries, industriesAz: after.industriesAz }),
    design: diffCount(before.design || {}, after.design || {}),
    settings: diffCount({ settings: before.settings || {}, features: before.features || {}, analytics: before.analytics || {}, structured: before.structured || {} },
      { settings: after.settings || {}, features: after.features || {}, analytics: after.analytics || {}, structured: after.structured || {} })
  };
}

/* ---------- auth ---------- */
function hashPassword(pw, salt){
  salt = salt || crypto.randomBytes(16).toString('hex');
  const hash = crypto.scryptSync(String(pw), salt, 64).toString('hex');
  return { salt, hash };
}
function verifyPassword(pw, rec){
  if (!rec || !rec.salt || !rec.hash) return false;
  const h = crypto.scryptSync(String(pw), rec.salt, 64);
  const stored = Buffer.from(rec.hash, 'hex');
  return h.length === stored.length && crypto.timingSafeEqual(h, stored);
}
function loadAdmin(){
  let admin = readJson(ADMIN_JSON, null);
  if (admin && admin.hash && admin.secret) return { admin, generated: null };
  const pw = process.env.ADMIN_PASSWORD || crypto.randomBytes(9).toString('base64').replace(/[^a-zA-Z0-9]/g, '').slice(0, 12);
  admin = Object.assign(hashPassword(pw), { secret: crypto.randomBytes(32).toString('hex'), createdAt: new Date().toISOString() });
  writeJsonAtomic(ADMIN_JSON, admin);
  return { admin, generated: process.env.ADMIN_PASSWORD ? null : pw };
}
let ADMIN = null;
function sign(payload){
  const body = Buffer.from(JSON.stringify(payload)).toString('base64url');
  const sig = crypto.createHmac('sha256', ADMIN.secret).update(body).digest('base64url');
  return body + '.' + sig;
}
function verifyToken(tok){
  if (!tok || typeof tok !== 'string') return null;
  const i = tok.lastIndexOf('.');
  if (i < 0) return null;
  const body = tok.slice(0, i), sig = tok.slice(i + 1);
  const want = crypto.createHmac('sha256', ADMIN.secret).update(body).digest('base64url');
  if (sig.length !== want.length || !crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(want))) return null;
  try {
    const p = JSON.parse(Buffer.from(body, 'base64url').toString('utf8'));
    if (!p.exp || p.exp < Date.now() || p.v !== ADMIN.createdAt) return null;
    return p;
  } catch (e) { return null; }
}
function parseCookies(req){
  const out = {};
  (req.headers.cookie || '').split(';').forEach(c => {
    const i = c.indexOf('=');
    if (i > 0) out[c.slice(0, i).trim()] = decodeURIComponent(c.slice(i + 1).trim());
  });
  return out;
}
function isAuthed(req){ return !!verifyToken(parseCookies(req)[COOKIE]); }
/* HTTPS is terminated by the platform / reverse proxy; it tells us via
   x-forwarded-proto. SECURE_COOKIES=1 forces the flag on. */
function isSecure(req){
  return process.env.SECURE_COOKIES === '1' || req.headers['x-forwarded-proto'] === 'https';
}
function sessionCookie(tok, maxAgeSec, secure){
  return COOKIE + '=' + encodeURIComponent(tok) + '; Path=/; HttpOnly; SameSite=Strict; Max-Age=' + maxAgeSec + (secure ? '; Secure' : '');
}

/* simple per-IP throttles: login (10 / 15 min), form submissions (30 / 10 min) */
function limiter(max, windowMs){
  const hits = new Map();
  return ip => {
    const now = Date.now();
    let rec = hits.get(ip);
    if (!rec || rec.reset < now){ rec = { count: 0, reset: now + windowMs }; hits.set(ip, rec); }
    rec.count++;
    if (hits.size > 5000) for (const [k, v] of hits) if (v.reset < now) hits.delete(k);
    return rec.count <= max;
  };
}
const loginLimiter = limiter(10, 15 * 60 * 1000);
const submitLimiter = limiter(30, 10 * 60 * 1000);

/* ---------- http helpers ---------- */
function send(res, status, body, headers){
  const h = Object.assign({
    'X-Content-Type-Options': 'nosniff',
    'X-Frame-Options': 'SAMEORIGIN',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=()'
  }, headers || {});
  if (typeof body === 'string' || Buffer.isBuffer(body)) h['Content-Length'] = Buffer.byteLength(body);
  res.writeHead(status, h);
  res.end(body);
}
function json(res, status, obj, headers){
  send(res, status, JSON.stringify(obj), Object.assign({ 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' }, headers || {}));
}
function readBody(req){
  return new Promise((resolve, reject) => {
    let size = 0; const chunks = [];
    req.on('data', c => {
      size += c.length;
      if (size > MAX_BODY){ reject(new Error('payload too large')); req.destroy(); return; }
      chunks.push(c);
    });
    req.on('end', () => {
      const raw = Buffer.concat(chunks).toString('utf8');
      if (!raw) return resolve({});
      try { resolve(JSON.parse(raw)); } catch (e) { reject(new Error('invalid JSON')); }
    });
    req.on('error', reject);
  });
}
/* Mutating requests must come from our own pages: SameSite=Strict cookie
   plus a custom header (no cross-site form can set one) plus an Origin check. */
function sameOrigin(req){
  if (req.headers['x-requested-with'] !== 'OmniAdmin') return false;
  const origin = req.headers.origin;
  if (!origin) return true;
  try { return new URL(origin).host === req.headers.host; } catch (e) { return false; }
}
/* behind a reverse proxy every visitor shares the proxy's socket address —
   set TRUST_PROXY=1 there so the throttles key on the real client */
function clientIp(req){
  if (TRUST_PROXY){
    const xff = String(req.headers['x-forwarded-for'] || '').split(',')[0].trim();
    if (xff) return xff;
  }
  return (req.socket && req.socket.remoteAddress) || '0.0.0.0';
}

/* ---------- submission notifications ----------
   Secrets live in the environment, never in site.json (which is public).
     RESEND_API_KEY + NOTIFY_EMAIL_TO [+ NOTIFY_EMAIL_FROM]  → email via api.resend.com
     NOTIFY_WEBHOOK_URL                                       → JSON POST (Slack, Zapier, Make, a CRM)
   Fire-and-forget after the submission is on disk; failures are logged,
   never surfaced to the visitor. */
function notifyConfig(){
  return {
    email: !!(process.env.RESEND_API_KEY && process.env.NOTIFY_EMAIL_TO),
    webhook: /^https:\/\//i.test(process.env.NOTIFY_WEBHOOK_URL || ''),
    autoReply: !!process.env.RESEND_API_KEY
  };
}
async function postWithTimeout(url, headers, body){
  const ctl = new AbortController();
  const timer = setTimeout(() => ctl.abort(), 8000);
  try {
    const r = await fetch(url, { method: 'POST', headers, body: JSON.stringify(body), signal: ctl.signal });
    if (!r.ok) throw new Error('HTTP ' + r.status + ' ' + (await r.text()).slice(0, 200));
  } finally { clearTimeout(timer); }
}
function notify(sub, site){
  const cfg = notifyConfig();
  const name = String((site.settings && site.settings.siteName) || 'OmniMark').replace(/[\r\n]+/g, ' ').trim().slice(0, 100) || 'OmniMark';
  const sender = process.env.NOTIFY_EMAIL_FROM || (name + ' <onboarding@resend.dev>');
  const resendUrl = process.env.RESEND_API_URL || 'https://api.resend.com/emails';
  const resendHeaders = { 'Content-Type': 'application/json', Authorization: 'Bearer ' + process.env.RESEND_API_KEY };
  const lines = Object.keys(sub.fields).map(k => k + ': ' + sub.fields[k]).join('\n');
  const text = 'New ' + sub.form + ' submission on ' + name + '\n' + sub.at + '\n\n' + lines + '\n\nPage: ' + sub.page + '\nLanguage: ' + sub.lang;
  if (cfg.webhook){
    postWithTimeout(process.env.NOTIFY_WEBHOOK_URL, { 'Content-Type': 'application/json' },
      { text, site: name, form: sub.form, at: sub.at, page: sub.page, lang: sub.lang, fields: sub.fields, id: sub.id,
        consentAt: sub.consentAt, consentSource: sub.consentSource })
      .catch(e => console.error('[notify] webhook failed:', e.message));
  }
  if (cfg.email){
    postWithTimeout(resendUrl, resendHeaders,
      { from: sender,
        to: process.env.NOTIFY_EMAIL_TO.split(',').map(s => s.trim()).filter(Boolean),
        reply_to: sub.fields.email || undefined,
        subject: '[' + name + '] New ' + sub.form + ' submission' + (sub.fields.name ? ' from ' + sub.fields.name : ''),
        text })
      .catch(e => console.error('[notify] email failed:', e.message));
  }
  if (cfg.autoReply && sub.fields.email){
    const firstName = String(sub.fields.name || '').replace(/[\r\n]+/g, ' ').trim().split(/\s+/)[0].slice(0, 80);
    const hello = firstName ? 'Hi ' + firstName + ',' : 'Hello,';
    let subject, replyText;
    if (sub.form === 'newsletter'){
      const mailbox = (site.settings && site.settings.email) || String(process.env.NOTIFY_EMAIL_TO || '').split(',')[0].trim();
      const unsubscribe = mailbox ? 'mailto:' + mailbox + '?subject=' + encodeURIComponent('Unsubscribe from ' + name) : '';
      subject = 'Welcome to ' + name;
      replyText = hello + '\n\nThanks for subscribing. We have recorded your signup and will send updates to this address.' +
        (unsubscribe ? '\n\nTo unsubscribe at any time, use this link: ' + unsubscribe : '') +
        '\n\n' + name;
    } else {
      subject = 'We received your enquiry — ' + name;
      replyText = hello + '\n\nThanks for contacting ' + name + '. Your enquiry is safely in our queue, and we will reply within one business day.\n\nThis is an automated confirmation; you can reply directly if you need to add context.\n\n' + name;
    }
    postWithTimeout(resendUrl, resendHeaders,
      { from: sender, to: [sub.fields.email], reply_to: (site.settings && site.settings.email) || undefined, subject, text: replyText })
      .catch(e => console.error('[notify] visitor acknowledgement failed:', e.message));
  }
}

function submissionErrors(form, fields){
  const rules = {
    contact: ['name', 'email', 'company', 'spend', 'consent'],
    teardown: ['name', 'email', 'company', 'spend'],
    newsletter: ['email']
  };
  if (!rules[form]) return null;
  const errors = {};
  for (const field of rules[form]){
    if (field === 'consent'){
      if (fields[field] !== 'true') errors[field] = 'consent required';
    } else if (!String(fields[field] || '').trim()) errors[field] = 'required';
  }
  const email = String(fields.email || '').trim();
  if (email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) errors.email = 'invalid email';
  return errors;
}

/* ---------- page metadata for the admin "Pages" tab ---------- */
function stripTags(s){ return s.replace(/<[^>]+>/g, '').replace(/&amp;/g, '&').replace(/&nbsp;/g, ' ').replace(/\s+/g, ' ').trim(); }
function pageInfo(file){
  const html = fs.readFileSync(path.join(ROOT, file), 'utf8');
  const title = (html.match(/<title>([^<]*)<\/title>/i) || [, ''])[1].trim();
  const description = (html.match(/<meta\s+name="description"\s+content="([^"]*)"/i) || [, ''])[1];
  const sections = [];
  const re = /<(section|header)\b[^>]*\bdata-section="([^"]+)"[^>]*>/g;
  let m;
  while ((m = re.exec(html))){
    const end = html.indexOf('</' + m[1] + '>', m.index);
    const inner = html.slice(m.index, end > 0 ? end : m.index + 4000);
    const lab = inner.match(/<(h1|h2|h3)\b[^>]*>([\s\S]*?)<\/\1>/i) || inner.match(/<p class="(?:eyebrow|label)[^"]*"[^>]*>([\s\S]*?)<\/p>/i);
    const aria = m[0].match(/aria-label="([^"]+)"/);
    let label = lab ? stripTags(lab[lab.length - 1]) : (aria ? aria[1] : '');
    if (m[1] === 'header') label = 'Hero' + (label ? ' — ' + label : '');
    sections.push({ key: m[2], label: (label || m[2]).slice(0, 90) });
  }
  return { key: file.replace(/\.html$/i, ''), file, title, description, sections };
}

function structuredData(html, key, site, base, loc){
  if (!base || !loc) return null;
  const settings = site.settings || {};
  const cfg = site.structured || {};
  const orgId = base + '/#organization';
  const org = {
    '@type': 'Organization', '@id': orgId,
    name: settings.siteName || 'OmniMark', url: base
  };
  if (cfg.orgLegalName) org.legalName = cfg.orgLegalName;
  if (cfg.orgLogoUrl) org.logo = cfg.orgLogoUrl;
  if (/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(settings.email || '')) org.email = settings.email;
  if (settings.phone) org.telephone = settings.phone;
  if (settings.address) org.address = { '@type': 'PostalAddress', streetAddress: settings.address };
  if (/^https?:\/\//i.test(settings.linkedin || '')) org.sameAs = [settings.linkedin];
  const graph = [org];

  if (key === 'article' && cfg.articleAuthor && cfg.articleDatePublished){
    const h1 = html.match(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i);
    const desc = ((site.pages && site.pages.article && site.pages.article.description) || ((html.match(/<meta\s+name="description"\s+content="([^"]*)"/i) || [])[1]) || '').trim();
    const article = {
      '@type': 'Article', '@id': loc + '#article', mainEntityOfPage: loc,
      headline: stripTags(h1 ? h1[1] : ''), datePublished: cfg.articleDatePublished,
      author: { '@type': 'Person', name: cfg.articleAuthor },
      publisher: { '@id': orgId }
    };
    if (desc) article.description = stripTags(desc);
    if (cfg.articleDateModified) article.dateModified = cfg.articleDateModified;
    if (settings.ogImage) article.image = settings.ogImage;
    graph.push(article);
  }

  const jobReady = key === 'role-detail' && ['jobTitle', 'jobDescription', 'jobDatePosted', 'jobValidThrough', 'jobEmploymentType', 'jobLocation', 'jobApplyUrl'].every(k => cfg[k]);
  if (jobReady){
    const job = {
      '@type': 'JobPosting', '@id': loc + '#job', title: cfg.jobTitle,
      description: cfg.jobDescription, datePosted: cfg.jobDatePosted,
      validThrough: cfg.jobValidThrough, employmentType: cfg.jobEmploymentType,
      hiringOrganization: { '@id': orgId }, url: cfg.jobApplyUrl,
      jobLocation: { '@type': 'Place', address: { '@type': 'PostalAddress', addressLocality: cfg.jobLocation } }
    };
    if (cfg.jobRemote) job.jobLocationType = 'TELECOMMUTE';
    graph.push(job);
  }
  return { '@context': 'https://schema.org', '@graph': graph };
}

function jsonLd(value){
  return JSON.stringify(value).replace(/</g, '\\u003c').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
}

/* Inject admin-set title / description / og into a page as it is served. */
function injectMeta(html, key, site){
  const pg = (site.pages && site.pages[key]) || {};
  if (pg.title){
    const t = escapeHtml(pg.title);
    html = html.replace(/<title>[^<]*<\/title>/i, '<title>' + t + '</title>')
               .replace(/(<meta\s+property="og:title"\s+content=")[^"]*(")/i, '$1' + t + '$2');
  }
  if (pg.description){
    const d = escapeHtml(pg.description);
    html = html.replace(/(<meta\s+name="description"\s+content=")[^"]*(")/i, '$1' + d + '$2')
               .replace(/(<meta\s+property="og:description"\s+content=")[^"]*(")/i, '$1' + d + '$2');
  }
  /* canonical / social tags for every page, derived from Settings */
  const base = String((site.settings && site.settings.siteUrl) || '').replace(/\/+$/, '');
  const extra = [];
  const loc = base ? base + '/' + (key === 'index' ? '' : key + '.html') : '';
  if (base && !/rel="canonical"/i.test(html)){
    extra.push('<link rel="canonical" href="' + escapeHtml(loc) + '">');
    extra.push('<meta property="og:url" content="' + escapeHtml(loc) + '">');
  }
  const img = site.settings && site.settings.ogImage;
  if (img && !/property="og:image"/i.test(html)) extra.push('<meta property="og:image" content="' + escapeHtml(img) + '">');
  if (!/name="twitter:card"/i.test(html)) extra.push('<meta name="twitter:card" content="' + (img ? 'summary_large_image' : 'summary') + '">');
  const schema = structuredData(html, key, site, base, loc);
  if (schema) extra.push('<script type="application/ld+json">' + jsonLd(schema) + '</script>');
  if (extra.length) html = html.replace(/<\/head>/i, extra.join('\n') + '\n</head>');
  return html;
}

/* ---------- API ---------- */
async function api(req, res, url){
  const p = url.pathname.replace(/^\/api/, '');
  const method = req.method;

  if (p === '/site' && method === 'GET') return json(res, 200, loadSite());
  if (p === '/me' && method === 'GET') return json(res, 200, { authed: isAuthed(req) });

  if (p === '/submit' && method === 'POST'){
    if (!submitLimiter(clientIp(req))) return json(res, 429, { error: 'Too many submissions, try again later.' });
    let body;
    try { body = await readBody(req); } catch (e) { return json(res, 400, { error: e.message }); }
    const form = String(body.form || 'form').replace(/[^a-z0-9-]/gi, '').slice(0, 30) || 'form';
    if (!['contact', 'teardown', 'newsletter'].includes(form)) return json(res, 400, { error: 'unsupported form' });
    const fields = {};
    for (const k of Object.keys(body)){
      if (k === 'form' || k === 'lang' || k === 'page') continue;
      const v = body[k];
      if (typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean') fields[k.slice(0, 60)] = String(v).slice(0, 5000);
    }
    const errors = submissionErrors(form, fields);
    if (errors && Object.keys(errors).length) return json(res, 400, { error: 'validation failed', fields: errors });
    fields.email = fields.email.trim().toLowerCase();
    const subs = readJson(SUBS_JSON, []);
    const sub = { id: crypto.randomBytes(8).toString('hex'), form, fields, at: new Date().toISOString(), lang: String(body.lang || 'en').slice(0, 5), page: String(body.page || '').slice(0, 200) };
    if (form === 'newsletter'){
      sub.consentAt = sub.at;
      sub.consentSource = 'footer-newsletter-form';
    }
    subs.push(sub);
    if (subs.length > 10000) subs.splice(0, subs.length - 10000);
    writeJsonAtomic(SUBS_JSON, subs);
    notify(sub, loadSite());
    return json(res, 200, { ok: true });
  }

  if (p === '/login' && method === 'POST'){
    if (!sameOrigin(req)) return json(res, 403, { error: 'forbidden' });
    if (!loginLimiter(clientIp(req))) return json(res, 429, { error: 'Too many attempts. Wait 15 minutes.' });
    let body;
    try { body = await readBody(req); } catch (e) { return json(res, 400, { error: e.message }); }
    if (!verifyPassword(body.password || '', ADMIN)) return json(res, 401, { error: 'Wrong password.' });
    const tok = sign({ exp: Date.now() + SESSION_TTL, v: ADMIN.createdAt, n: crypto.randomBytes(6).toString('hex') });
    return json(res, 200, { ok: true }, { 'Set-Cookie': sessionCookie(tok, SESSION_TTL / 1000, isSecure(req)) });
  }
  if (p === '/logout' && method === 'POST'){
    return json(res, 200, { ok: true }, { 'Set-Cookie': sessionCookie('', 0, isSecure(req)) });
  }

  /* ---- everything below needs a session ---- */
  if (!isAuthed(req)) return json(res, 401, { error: 'Not signed in.' });
  if (method !== 'GET' && !sameOrigin(req)) return json(res, 403, { error: 'forbidden' });

  if (p === '/site' && method === 'PUT'){
    let body;
    try { body = await readBody(req); } catch (e) { return json(res, 400, { error: e.message }); }
    let site;
    try { site = validateSite(body); } catch (e) { return json(res, 400, { error: e.message }); }
    saveSite(site);
    return json(res, 200, { ok: true, site });
  }
  if (p === '/draft' && method === 'GET'){
    const record = readDraft();
    return json(res, 200, { draft: record ? record.draft : null, savedAt: record ? record.savedAt : null, live: loadSite() });
  }
  if (p === '/draft' && method === 'PUT'){
    let body;
    try { body = await readBody(req); } catch (e) { return json(res, 400, { error: e.message }); }
    let draft;
    try { draft = validateSite(body); } catch (e) { return json(res, 400, { error: e.message }); }
    const savedAt = new Date().toISOString();
    writeJsonAtomic(DRAFT_JSON, { savedAt, draft });
    return json(res, 200, { ok: true, savedAt });
  }
  if (p === '/draft' && method === 'DELETE'){
    removeDraft();
    return json(res, 200, { ok: true });
  }
  if (p === '/publish' && method === 'POST'){
    const record = readDraft();
    if (!record) return json(res, 409, { error: 'No draft to publish.' });
    let site;
    try { site = validateSite(record.draft); } catch (e) { return json(res, 400, { error: e.message }); }
    const summary = publishSummary(loadSite(), site);
    saveSite(site);
    removeDraft();
    return json(res, 200, { ok: true, site, summary });
  }
  if (p === '/status' && method === 'GET'){
    return json(res, 200, { notifications: notifyConfig(), trustProxy: TRUST_PROXY, secure: isSecure(req), node: process.version });
  }
  if (p === '/pages' && method === 'GET'){
    return json(res, 200, listPages().map(pageInfo));
  }
  if (p === '/submissions' && method === 'GET'){
    return json(res, 200, readJson(SUBS_JSON, []).slice().reverse());
  }
  const del = p.match(/^\/submissions\/([a-f0-9]{16})$/);
  if (del && method === 'PATCH'){
    let body;
    try { body = await readBody(req); } catch (e) { return json(res, 400, { error: e.message }); }
    if (typeof body.read !== 'boolean') return json(res, 400, { error: 'read must be true or false' });
    const subs = readJson(SUBS_JSON, []);
    const sub = subs.find(s => s.id === del[1]);
    if (!sub) return json(res, 404, { error: 'Submission not found.' });
    sub.read = body.read;
    writeJsonAtomic(SUBS_JSON, subs);
    return json(res, 200, { ok: true, submission: sub });
  }
  if (del && method === 'DELETE'){
    const subs = readJson(SUBS_JSON, []);
    const next = subs.filter(s => s.id !== del[1]);
    writeJsonAtomic(SUBS_JSON, next);
    return json(res, 200, { ok: true, removed: subs.length - next.length });
  }
  if (p === '/submissions' && method === 'DELETE'){
    writeJsonAtomic(SUBS_JSON, []);
    return json(res, 200, { ok: true });
  }
  if (p === '/password' && method === 'POST'){
    let body;
    try { body = await readBody(req); } catch (e) { return json(res, 400, { error: e.message }); }
    if (!verifyPassword(body.current || '', ADMIN)) return json(res, 401, { error: 'Current password is wrong.' });
    const next = String(body.next || '');
    if (next.length < 8) return json(res, 400, { error: 'New password must be at least 8 characters.' });
    ADMIN = Object.assign({}, ADMIN, hashPassword(next), { secret: crypto.randomBytes(32).toString('hex'), createdAt: new Date().toISOString() });
    writeJsonAtomic(ADMIN_JSON, ADMIN);
    const tok = sign({ exp: Date.now() + SESSION_TTL, v: ADMIN.createdAt, n: crypto.randomBytes(6).toString('hex') });
    return json(res, 200, { ok: true }, { 'Set-Cookie': sessionCookie(tok, SESSION_TTL / 1000, isSecure(req)) });
  }
  return json(res, 404, { error: 'no such endpoint' });
}

/* ---------- static files ---------- */
function serveStatic(req, res, url){
  let pathname;
  try { pathname = decodeURIComponent(url.pathname); } catch (e) { return send(res, 400, 'Bad request'); }
  if (pathname.includes('\0')) return send(res, 400, 'Bad request');
  if (pathname === '/') pathname = '/index.html';
  if (pathname === '/sitemap.xml' && !fs.existsSync(path.join(ROOT, 'sitemap.xml'))) writeSeoFiles(loadSite());

  let file = path.normalize(path.join(ROOT, pathname));
  if (!file.startsWith(ROOT + path.sep) && file !== ROOT) return send(res, 403, 'Forbidden');
  const rel = path.relative(ROOT, file).split(path.sep);
  if (rel[0] === 'data' && PRIVATE_FILES.has(rel[1])) return send(res, 403, 'Forbidden');
  if (rel[0].startsWith('.') || rel[0] === 'node_modules' || rel[0] === 'server.js' || rel[0] === 'package.json') return send(res, 404, 'Not found');

  /* clean URLs: /about -> about.html */
  if (!fs.existsSync(file) && !path.extname(file) && fs.existsSync(file + '.html')) file += '.html';

  let stat;
  try { stat = fs.statSync(file); } catch (e) { stat = null; }
  if (stat && stat.isDirectory()){ file = path.join(file, 'index.html'); try { stat = fs.statSync(file); } catch (e) { stat = null; } }
  if (!stat){
    const nf = path.join(ROOT, '404.html');
    if (fs.existsSync(nf)) return send(res, 404, fs.readFileSync(nf), { 'Content-Type': MIME['.html'], 'Cache-Control': 'no-store' });
    return send(res, 404, 'Not found');
  }
  if (req.method !== 'GET' && req.method !== 'HEAD') return send(res, 405, 'Method not allowed');

  const ext = path.extname(file).toLowerCase();
  const type = MIME[ext] || 'application/octet-stream';
  if (ext === '.html'){
    const key = path.basename(file, '.html');
    let html = injectMeta(fs.readFileSync(file, 'utf8'), key, loadSite());
    if (url.searchParams.get('edit') === '1' && isAuthed(req) && !['admin', 'admin-advanced', '404'].includes(key)){
      html = html.replace(/<\/body>/i,
        '<link rel="stylesheet" href="css/editor.css">\n<script src="js/editor.js" defer></script>\n</body>');
    }
    return send(res, 200, html, { 'Content-Type': type, 'Cache-Control': 'no-cache' });
  }
  const cache = (rel[0] === 'data') ? 'no-cache' : 'public, max-age=300';
  send(res, 200, fs.readFileSync(file), { 'Content-Type': type, 'Cache-Control': cache });
}

/* ---------- boot ---------- */
function main(){
  fs.mkdirSync(DATA, { recursive: true });
  const boot = loadAdmin();
  ADMIN = boot.admin;
  if (!fs.existsSync(SITE_JSON)) saveSite(loadSite());
  else if (!fs.existsSync(SITE_JS)) fs.writeFileSync(SITE_JS, siteToJs(loadSite()));

  const server = http.createServer((req, res) => {
    const url = new URL(req.url, 'http://' + (req.headers.host || 'localhost'));
    if (isSecure(req)) res.setHeader('Strict-Transport-Security', 'max-age=31536000; includeSubDomains');
    if (url.pathname.startsWith('/api/') || url.pathname === '/api'){
      api(req, res, url).catch(err => { console.error(err); json(res, 500, { error: 'server error' }); });
      return;
    }
    try { serveStatic(req, res, url); } catch (err) { console.error(err); send(res, 500, 'Server error'); }
  });
  server.listen(PORT, HOST, () => {
    const base = 'http://' + (HOST === '0.0.0.0' ? 'localhost' : HOST) + ':' + PORT;
    console.log('OmniMark site   →  ' + base + '/');
    console.log('Admin dashboard →  ' + base + '/admin');
    const n = notifyConfig();
    console.log('Notifications   →  email ' + (n.email ? 'on' : 'off') + ', webhook ' + (n.webhook ? 'on' : 'off') + ', visitor acknowledgement ' + (n.autoReply ? 'on' : 'off') +
      (n.email || n.webhook ? '' : '   (set RESEND_API_KEY + NOTIFY_EMAIL_TO and/or NOTIFY_WEBHOOK_URL)'));
    if (boot.generated){
      console.log('\nFirst run: generated admin password  →  ' + boot.generated);
      console.log('Change it from Admin → Account. (Stored hashed in data/admin.json.)\n');
    }
  });
}
if (require.main === module) main();
module.exports = { validateSite, siteToJs, injectMeta, pageInfo };
